# Generated by Django 4.0.1 on 2022-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=15)),
                ('PIN', models.CharField(max_length=4)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
