# Generated by Django 4.0.1 on 2022-01-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='customer',
        ),
    ]
