# Generated by Django 4.0.1 on 2022-01-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('account_number', models.CharField(max_length=15)),
                ('Current_PIN', models.CharField(max_length=4)),
                ('New_PIN', models.CharField(max_length=4)),
            ],
        ),
    ]
