# Generated by Django 4.0.1 on 2022-01-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0004_remove_register_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
