# Generated by Django 4.0.1 on 2022-01-17 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0009_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='unique_code_s',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
