# Generated by Django 4.0 on 2022-05-03 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0010_alter_transaction_unique_code_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
