# Generated by Django 4.0 on 2022-05-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0013_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
