# Generated by Django 4.0 on 2022-05-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0014_remove_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='statuss',
            field=models.IntegerField(default=2),
        ),
    ]
