# Generated by Django 4.0 on 2022-05-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0016_alter_transaction_statuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='statuss',
            field=models.IntegerField(default=2),
        ),
    ]
