# Generated by Django 4.0 on 2022-05-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0017_alter_transaction_statuss'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmation',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='statuss',
        ),
    ]
